# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ebe4e6a17804969c178bdebb62d9c5a096279e3b160df927ed5027c6c142bc9758c0505d1f390637c469ab215ab45f5af269657aaa47767c20f31829fc10296

test:
  secret_key_base: e5f18b3bb37864c5aeb95f50869136f8c14e459c97a26dfe4cb43bd2f136d33ce10ef2536880b35a6c196a115348c22b26214b6f677ad6cc214f97f0e6d2efb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
